
server.port=8000
#spring.application.name=Spring Boot Admin Web
#spring.boot.admin.discovery.enabled=true
#spring.application.admin.enabled=true
#spring.boot.admin.url=http://localhost:${server.port}
#spring.application.admin.enabled=true

#spring.jackson.serialization.indent_output=true
#endpoints.health.sensitive=false
